language: objective-c
osx_image: xcode8.3
script:
  - xcodebuild test -scheme MyFirstTravis -configuration Debug -destination 'platform=iOS Simulator,OS=10.3,name=iPhone 7 Plus' | bundle exec xcpretty -c