language: objective-c  # Swiftだけどobjective-cを指定
osx_image: xcode8.3.3  # 使っているXcodeのバージョン
script:
  # テストを実行(schemeにスキーム名を指定するよ)
  - xcodebuild test -scheme MyFirstTravis -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7'
notifications:
  email: false         # メール通知はOFF